### PR TITLE
Provide setup.py for pip installation

### PR DESCRIPTION
**Pull request by koreyou**
Add support for pip installation (#27 ).

 9e75085 did not quite fix the problem because this project relies on Implicit Namespace Packages (which a lot of setuptools does not support yet).
I added `__init__.py` to fix this problem.

Also, I added CLI command so you can run CLI command `mtool` instead of `./main.py`.

### CODE REVIEW

**Comment by oepen** [comment]
i am pretty much a python novice, so please allow me to ask some clarification questions.

+ can we avoid a file by the name ‘_version.py’; why not just ‘version.py’?
+ what is the benefit of wrapping in a main function()?
+ will it be easy for people to continuosly ‘pull’ updates, or will we have to bump the version number (or make some kind of release) everytime we make a change i would want folks to get as soon as possible?

just now, the software is still evolving very quickly, so i would not put unnecessary obstacles into rolling out revisions easily :-).

many thanks for your support!

**Comment by koreyou** [comment]
Sure things!

> can we avoid a file by the name ‘_version.py’; why not just ‘version.py’?

The name `_version.py` is just a convention of python packages, to hide a module that users are not meant to import directly (prefix '_' and '__' denotes that user should not use the module directly).
So, yeah,`version.py` is just fine (though I recommend you follow convention).

> what is the benefit of wrapping in a main function()?

As [setup.py requires a function](https://github.com/koreyou/mtool/blob/impl_setup/setup.py#L29) instead of a module to use CLI interface, I wrapped it in a function.
That way user can choose to use `main()` via `./main.py` or `import main; main.main()` (as setuptools do).

> will it be easy for people to continuosly ‘pull’ updates, or will we have to bump the version number (or make some kind of release) everytime we make a change i would want folks to get as soon as possible?

Yes. You can always `pip install -U git+https://github.com/cfmrp/mtool.git` to get the latest version.
Or, you can `pip install git+https://github.com/cfmrp/mtool.git@003fcd6c152698f6f14ce1edd57d495fbc774ee6` (which doesn't work because the PR is not yet merged) or `pip install git+https://github.com/cfmrp/mtool.git@TAG_NAME` to get a specific version.

Few things that you should note so as to not to break the code when updating the code are:

* Add `__init__.py` when creating new module. That include a case when you are adding a module inside a module (e.g. when you are making a module, say, `score.new_score_module`, you need to add `score/new_score_module/__init__.py`).
* When you are adding new file to root path (same depth as `main.py`), add it to `py_modules` in `setup.py`. You do not need this if you are adding a file to already existing module.

I also recommend you add some sort of versioning and update `_version.py` (or version.py) accordingly, but it is not compulsory unless you are registering the library to PyPI.


Anyhow, allowing pip install allows users to cleanly integrate mtool to their code and thus should definitely be included.

**Comment by oepen** [comment]
thanks; merged now (and i did rename to 'version.py').

i am guessing the main purpose of the version file is to have that statement in a single place, right?  so what would be the right way of using it in 'setup.py'?  is there any significance to the current 'release' and 'version' top-level variables?  could i instead just say version = __version__ within setuptools.setup(...)?

my apologies for abusing you as a python tutor :-)!  please do feel free to just point me to the relevant documentation.

**Comment by koreyou** [comment]
No problems.

> i am guessing the main purpose of the version file is to have that statement in a single place, right? so what would be the right way of using it in 'setup.py'? is there any significance to the current 'release' and 'version' top-level variables? 

Yes. The main purpose of the version file is to have that statement in a single place.
If you have single namespace (as most library should, but `mtool` currently does not), you [should](https://www.python.org/dev/peps/pep-0396/) provide `__version__` in the namespace which can be obtained from the `version.py`.
And you may want to add a command `mtool --version` in the future, in which case you also need to obtain version number from `version.py`.

> could i instead just say version = version within setuptools.setup(...)?

Yes, for now, but I recommend separating the file for the future.
`mtool` is currently under heavy development anyway so versioning is not really working.
So, yeah, you can keep whatever the way you like for now. It does not break anything.

**Pull request merged**
